services:
  mongodb:
    image: 'mongo:latest'
    container_name: 'mongodb'
    environment:
      MONGO_INITDB_DATABASE: 'gymanalyticsdb'
      MONGO_INITDB_ROOT_USERNAME: 'admin'
      MONGO_INITDB_ROOT_PASSWORD: 'admin'
    ports:
      - '27017:27017'
